# An array of paths to watch for new content.
pathsToWatch:
  "/home/vagrant/test":
    remotePath: '/backups/somefolder'
privateKeyPath: /home/vagrant/vagrant-privatekey.rsa
remoteUser: vagrant
remoteHost: 33.33.33.40
remotePort: 22
# An array fo file extensions to exclude from triggering a scan.
# fileTypesToExclude: [
#   "nfo",
#   "tbn"
# ]
# ignoreHiddenFiles: true
